---
- hosts: all
  gather_facts: no
  tasks:
   # To use the lookup plugin, filter plugin, vars plugin, or the load_vars action,
   # you need sops installed on localhost:
   - name: Install sops on localhost
     ansible.builtin.include_role:
       name: community.sops.install
     vars:
       sops_install_on_localhost: true
